# Generated by Django 5.0.1 on 2024-01-28 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
        ('car', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='author.authormodel'),
        ),
    ]
