# Generated by Django 5.0.1 on 2024-01-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_alter_carmodel_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
