# Generated by Django 5.0.1 on 2024-01-28 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_carmodel_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='author',
        ),
    ]
