# Generated by Django 5.0.1 on 2024-01-28 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_remove_carmodel_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
