# Generated by Django 5.0.1 on 2024-01-28 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0007_carmodel_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='count',
        ),
    ]
