# Generated by Django 5.0.1 on 2024-01-28 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0008_remove_carmodel_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
