# Generated by Django 5.0.1 on 2024-01-28 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
        ('car', '0004_alter_carmodel_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthorModel',
        ),
    ]
