# Generated by Django 5.0.1 on 2024-01-28 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthorModel',
        ),
    ]
